AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
